#!/bin/sh
# hope for the best

apk add podman

podman load /reprovision/coreos-installer.tar

podman run --privileged --rm \
    -v /dev:/dev -v /run/udev:/run/udev -v /reprovision:/data -w /data \
    quay.io/coreos/coreos-installer:release \
    install /dev/vdb -i ucore-ignition.ign --image-file coreos-image.qcow2.gz --offline

# gn
reboot