name: ucore-reprovisioning
run-name: "THOSE WHO ACTION: 💀💀💀💀💀💀"
on:
  push:
    paths:
      - "coreos-config.bu"
    branches:
      - main
jobs:
  build-config:
    name: Build Ignition config
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run Butane
        run: podman run --interactive --rm --security-opt label=disable --volume ${PWD}:/pwd --workdir /pwd quay.io/coreos/butane:release --pretty --strict coreos-config.bu > ucore-ignition.ign
  